"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { useState } from "react";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [visible, setVisible] = useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row px-4 py-5 space-x-10 xl:space-x-10">
          <Sidebar visible={visible}></Sidebar>
          <Navbar updateVisible={setVisible} state={visible}>
            {children}
          </Navbar>
        </div>
      </body>
    </html>
  );
}
